### PR TITLE
feat(config): Use LUACOV_CONFIG as default_config_file

### PR DESCRIPTION
**Pull request by broma0**
On the command line, users can specify the configuration file like `luacov -c config/luacov.lua`. 

When loading luacov like `lua -l luacov program.lua`, however, it seems like the config file is hardcoded to `.luacov`. 

This PR changes the default luacov file to `os.getenv("LUACOV_CONFIG") or ".luacov"`. 

This is similar to luarocks, which has the `LUAROCKS_CONFIG` environment variable.

### CODE REVIEW

**Comment by broma0** [comment]
@hishamhm - Please let me know if you'd like any changes on this

**Comment by broma0** [comment]
@Tieske - I see that you're also part of the parent project, can you help review and potentially merge this one-liner?

**Comment by Tieske** [comment]
this would at least need a doc update here; https://github.com/lunarmodules/luacov#configuration and maybe some tests (if there are some around the config file, didn't check)

**Comment by broma0** [comment]
Thanks @Tieske. I just updated the README and added tests.

**Comment by Tieske** [comment]
@broma0 the tests are failing on AppVeyor, can you fix them?

**Comment by broma0** [comment]
@Tieske - Classic "works on my machine" situation due to windows/linux differences in setting environment variables. It works now!

**Comment by broma0** [comment]
Hey @Tieske - please let me know if you'd like any more changes.

**Comment by broma0** [comment]
@Tieske, @hishamhm - Following up after a few weeks - is there anything I can do to help release this? I'd like to use this repo instead of my fork as soon as possible.

**Comment by Tieske** [comment]
Thx @broma0 for your contribution!

**Comment by broma0** [comment]
@Tieske / @hishamhm - Would you be able to publish this (and the other recent merges) to luarocks?

**Pull request merged**
